export const projects = [
  {
    id: 1,
    slug: "appic-media",
    title: "Appic Media",
    about: "Appic Media is a leading technology platform providing mobile advertising and analytics services.",
    skills: ["HTML5", "CSS3", "Bootstrap", "React.js","JavaScript (ES6+)","React Hooks",
  "React Router",
  "Bootstrap",
  "REST API Integration",
  "Axios",
  "Responsive Design",
  "Git"],
    roles: ["UI/UX Design",
  "Frontend Development (React)",
  "API Integration",
  "Responsive Design",
  "Performance Optimization",
  "Testing & Deployment"],
    image: "/images/project1.png",
    branding: [ "/images/1.jpg",
  "/images/2.jpg",
  "/images/3.jpg",
  "/images/4.jpg",
  "/images/5.jpg",
  "/images/6.jpg",
  "/images/7.jpg",
  "/images/8.jpg",
  "/images/4.jpg"]
  },
  {
    id: 2,
    slug: "aiven",
    title: "aiven Schooling",
    about: "Getting Quality Education is now more Easy STEM Infinite is here for you with various courses & materials from skilled tutors all around the world",
   skills: ["HTML5", "CSS3", "Bootstrap", "React.js","JavaScript (ES6+)","React Hooks",
  "React Router",
  "Bootstrap",
  "REST API Integration",
  "Axios",
  "Responsive Design",
  "Git"],
    roles: ["UI/UX Design",
  "Frontend Development (React)",
  "API Integration",
  "Responsive Design",
  "Performance Optimization",
  "Testing & Deployment"],
    image: "/images/project2.png",
     branding: [ "/images/1.jpg",
  "/images/2.jpg",
  "/images/3.jpg",
  "/images/4.jpg",
  "/images/5.jpg",
  "/images/6.jpg",
  "/images/7.jpg",
  "/images/8.jpg",
  "/images/4.jpg"]
  },
  {
    id: 3,
    slug: "aifactory",
    title: "AIFactory",
    about: "Where Transformers Power Your AI Products Join 5,000+ professionals mastering AI through hands-on training and real-world projects. Transfor your career in months, not years.",
   skills: ["HTML5", "CSS3", "Bootstrap", "React.js","JavaScript (ES6+)","React Hooks",
  "React Router",
  "Bootstrap",
  "REST API Integration",
  "Axios",
  "Responsive Design",
  "Git"],
    roles: ["UI/UX Design",
  "Frontend Development (React)",
  "API Integration",
  "Responsive Design",
  "Performance Optimization",
  "Testing & Deployment"],
    image: "/images/project3.png",
     branding: [ "/images/1.jpg",
  "/images/2.jpg",
  "/images/3.jpg",
  "/images/4.jpg",
  "/images/5.jpg",
  "/images/6.jpg",
  "/images/7.jpg",
  "/images/8.jpg",
  "/images/4.jpg"]
  }

];